[package]
name = "clima"
version = "0.0.9"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/clima"
description = "A minimal Markdown reader in the terminal"
edition = "2018"
keywords = ["cli", "markdown"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
clap = "2.33"
crossterm = "0.20"
custom_error = "1.9"
lazy_static = "1.4"
log = "0.4"
minimad = "0.8"
simplelog = "0.10"
termimad = "0.14.2"
terminal-light = "0.2"

[patch.crates-io]
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
# crossterm = { path = "../crossterm-rs/crossterm" }
