[package]
name = "clima"
version = "0.0.10"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/clima"
description = "A minimal Markdown reader in the terminal"
edition = "2018"
keywords = ["cli", "markdown"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
cfg-if = "1.0.0"
clap = "2.33"
crossterm = "0.21"
custom_error = "1.9"
lazy_static = "1.4"
log = "0.4"
minimad = "0.8"
reqwest = { version = "0.11.9", optional = true, features = ["blocking"]}
simplelog = "0.10"
tempfile = { version = "3.3.0", optional = true }
termimad = "0.14.2"
terminal-light = "0.5"

[features]
web = ["reqwest", "tempfile"]

[patch.crates-io]
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
# terminal-light = { path = "../terminal-light" }
# crossterm = { path = "../crossterm-rs/crossterm" }
