[package]
name = "clima"
version = "0.0.11-dev"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/clima"
description = "A minimal Markdown reader in the terminal"
edition = "2018"
keywords = ["cli", "markdown"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"

[dependencies]
clap = "2.33"
crossterm = "0.23.1"
custom_error = "1.9"
lazy-regex = "2.2.2"
lazy_static = "1.4"
log = "0.4"
minimad = "0.8"
reqwest = { version = "0.11.9", features = ["blocking"]}
simplelog = "0.10"
termimad = "0.20.1"
terminal-light = "0.8"

[patch.crates-io]
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
# terminal-light = { path = "../terminal-light" }
# crossterm = { path = "../crossterm-rs/crossterm" }
